/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author owner
 */
public class penjumlahan extends javax.swing.JPanel {

    /**
     * Creates new form penjumlahan
     */
    public penjumlahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("nilai 1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 11, -1, -1));

        jLabel2.setText("nilai 2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("hasil");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 195, -1, -1));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 11, 75, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 57, 84, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 192, 131, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer nilai1 = Integer.valueOf(jTextField1.getText());
        Integer nilai2 = Integer.valueOf(jTextField2.getText());
        int nilai3 = nilai1 + nilai2;

        String Hasil;
        Hasil = String.valueOf(nilai3);
jTextField3.setText(Hasil);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
